# Generated by Django 5.1.5 on 2025-01-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic', '0005_alter_menuitem_image_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
    ]
